"""AIC 2026 retrieval contracts and dataset tooling."""

from .contracts import (
    KeyframeRecord,
    Manifest,
    ManifestError,
    Task,
    VideoRecord,
    load_manifest,
    save_manifest,
)
from .evaluation import (
    EvaluationError,
    FrameInterval,
    KisGroundTruth,
    KisResponse,
    QaGroundTruth,
    QaResponse,
    QueryMetrics,
    TrakeGroundTruth,
    TrakeResponse,
    evaluate_ranked,
)
from .hybrid_retrieval import (
    HybridRetrievalConfig,
    HybridRetrievalError,
    HybridRetrievalResult,
    HybridRetrievalStatus,
    HybridTextRetriever,
)
from .ocr import (
    OcrArtifactMetadata,
    OcrError,
    OcrIndex,
    OcrMatch,
    OcrProvenance,
    OcrRecord,
    load_ocr_artifact,
    load_optional_ocr_artifact,
)
from .query_planning import (
    OrderedEvent,
    QueryPlan,
    QueryPlanningError,
    QwenQueryPlanner,
    VisualQuery,
)
from .qa import (
    ANSWER_TYPES,
    AnswerHypothesis,
    AutomaticQaPipeline,
    EvidenceWindow,
    FrameEvidence,
    QaError,
    QaPipeline,
    QaPipelineStatus,
    QaQuery,
    normalize_answer,
    parse_qa_query,
    route_answer_type,
)
from .qa_evidence import (
    EvidenceConfig,
    build_evidence_windows,
    decode_window,
    merge_ranked_hits,
    refine_evidence_windows,
    sample_frame_ids,
)
from .qa_models import AnswerEngine, FailClosedAnswerEngine, ParsedAnswer, parse_answer_protocol
from .trake import AlignmentConfig, TrakeEvent, TrakeQuery, align_event_hits, parse_trake_query
from .alignment import retrieve_and_align
from .query_pack import QueryPackDiagnostic, QueryPackEntry, load_query_pack, summarize_diagnostics
from .submission import build_submission_zip, write_submission_csv

__all__ = [
    "AlignmentConfig",
    "AnswerEngine",
    "AnswerHypothesis",
    "AutomaticQaPipeline",
    "EvidenceConfig",
    "EvidenceWindow",
    "EvaluationError",
    "FailClosedAnswerEngine",
    "FrameEvidence",
    "FrameInterval",
    "HybridRetrievalConfig",
    "HybridRetrievalError",
    "HybridRetrievalResult",
    "HybridRetrievalStatus",
    "HybridTextRetriever",
    "KeyframeRecord",
    "KisGroundTruth",
    "KisResponse",
    "Manifest",
    "ManifestError",
    "OcrArtifactMetadata",
    "OcrError",
    "OcrIndex",
    "OcrMatch",
    "OcrProvenance",
    "OcrRecord",
    "OrderedEvent",
    "ParsedAnswer",
    "QaError",
    "QaGroundTruth",
    "QaPipeline",
    "QaPipelineStatus",
    "QaQuery",
    "QaResponse",
    "QueryMetrics",
    "QueryPackDiagnostic",
    "QueryPackEntry",
    "QueryPlan",
    "QueryPlanningError",
    "QwenQueryPlanner",
    "Task",
    "TrakeEvent",
    "TrakeGroundTruth",
    "TrakeQuery",
    "TrakeResponse",
    "VideoRecord",
    "VisualQuery",
    "align_event_hits",
    "build_evidence_windows",
    "build_submission_zip",
    "decode_window",
    "evaluate_ranked",
    "load_manifest",
    "load_ocr_artifact",
    "load_optional_ocr_artifact",
    "merge_ranked_hits",
    "normalize_answer",
    "parse_answer_protocol",
    "parse_qa_query",
    "parse_trake_query",
    "refine_evidence_windows",
    "retrieve_and_align",
    "route_answer_type",
    "sample_frame_ids",
    "save_manifest",
    "summarize_diagnostics",
    "write_submission_csv",
]
